export interface BadgeData {
  id: string;
  label: string;
  description: string;     // one sentence, what the user did to earn it
  icon: string;            // single emoji
  tier: "seed" | "sprout" | "grove" | "canopy" | "storm" | "legend";
  category: "rank" | "streak" | "grid" | "quest" | "social" | "special";
  unlockCondition: string; // plain English e.g. "Reach 500 LP"
  aeroCreditsReward: number;
  unlocked?: boolean;
  unlockedAt?: string;     // ISO date string
  progress?: number;       // 0–100, shown if not yet unlocked
}

export const TIER_COLOURS: Record<string, { glow: string; bg: string; border: string }> = {
  seed:   { glow: '#4CAF50', bg: '#1B3A1F', border: '#4CAF50' },
  sprout: { glow: '#C8F500', bg: '#1C2A0A', border: '#C8F500' },
  grove:  { glow: '#00E5FF', bg: '#0A1F2A', border: '#00E5FF' },
  canopy: { glow: '#FFB800', bg: '#2A1A00', border: '#FFB800' },
  storm:  { glow: '#7C3AED', bg: '#1A0A2A', border: '#7C3AED' },
  legend: { glow: 'rainbow', bg: '#0D1B2A', border: 'conic-gradient' },
};

export const BADGES: BadgeData[] = [
  // ==================== SEED TIER ====================
  {
    id: "first_steps",
    label: "First Steps",
    description: "Completed your very first quest to start your leafstep journey.",
    icon: "👣",
    tier: "seed",
    category: "quest",
    unlockCondition: "Complete your first quest",
    aeroCreditsReward: 50,
    unlocked: false,
  },
  {
    id: "carbon_curious",
    label: "Carbon Curious",
    description: "Logged your first carbon footprint entry to measure your impact.",
    icon: "📝",
    tier: "seed",
    category: "rank",
    unlockCondition: "Log your first carbon footprint entry",
    aeroCreditsReward: 50,
    unlocked: false,
  },
  {
    id: "grid_watcher",
    label: "Grid Watcher",
    description: "Viewed your first grid load status alert to align your energy habits.",
    icon: "👀",
    tier: "seed",
    category: "grid",
    unlockCondition: "See your first grid load alert",
    aeroCreditsReward: 50,
    unlocked: false,
  },
  {
    id: "bamboo_planter",
    label: "Bamboo Planter",
    description: "Placed your first ecological bamboo structure in the virtual green city.",
    icon: "🎋",
    tier: "seed",
    category: "special",
    unlockCondition: "Place your first structure in the city",
    aeroCreditsReward: 50,
    unlocked: false,
  },

  // ==================== SPROUT TIER ====================
  {
    id: "sapling_steward",
    label: "Sapling Steward",
    description: "Passed a milestone of 500 total Leaf Points on your environmental journey.",
    icon: "🌱",
    tier: "sprout",
    category: "rank",
    unlockCondition: "Reach 500 LP",
    aeroCreditsReward: 100,
    unlocked: false,
  },
  {
    id: "eco_streak",
    label: "Eco Streak",
    description: "Maintained a continuous 3-day action streak of eco-friendly updates.",
    icon: "🔥",
    tier: "sprout",
    category: "streak",
    unlockCondition: "Maintain a 3-day action streak",
    aeroCreditsReward: 100,
    unlocked: false,
  },
  {
    id: "defer_starter",
    label: "Defer Starter",
    description: "Successfully deferred heavy appliance usage during intensive peak hours for the first time.",
    icon: "⏰",
    tier: "sprout",
    category: "grid",
    unlockCondition: "Defer an appliance during peak grid hours for the first time",
    aeroCreditsReward: 100,
    unlocked: false,
  },
  {
    id: "quest_runner",
    label: "Quest Runner",
    description: "Demonstrated early quest consistency by completing 5 quests in total.",
    icon: "🏃",
    tier: "sprout",
    category: "quest",
    unlockCondition: "Complete 5 quests total",
    aeroCreditsReward: 100,
    unlocked: false,
  },

  // ==================== GROVE TIER ====================
  {
    id: "grid_guardian",
    label: "Grid Guardian",
    description: "Deferred your home appliances 10 times to prevent peak load grid stress.",
    icon: "🛡️",
    tier: "grove",
    category: "grid",
    unlockCondition: "Defer 10 appliances during peak hours",
    aeroCreditsReward: 200,
    unlocked: false,
  },
  {
    id: "frequency_watcher",
    label: "Frequency Watcher",
    description: "Acted appropriately during 5 peak load smart grid alerts.",
    icon: "📡",
    tier: "grove",
    category: "grid",
    unlockCondition: "Act on 5 peak grid alerts",
    aeroCreditsReward: 200,
    unlocked: false,
  },
  {
    id: "carbon_cutter",
    label: "Carbon Cutter",
    description: "Directly reduced your personal carbon dioxide emissions by 10kg in a single month.",
    icon: "✂️",
    tier: "grove",
    category: "rank",
    unlockCondition: "Reduce personal CO2 by 10kg in one month",
    aeroCreditsReward: 200,
    unlocked: false,
  },
  {
    id: "night_owl",
    label: "Night Owl",
    description: "Shifted 3 high-energy appliance cycles to off-peak slots between 22:00 and 06:00.",
    icon: "🦉",
    tier: "grove",
    category: "grid",
    unlockCondition: "Shift 3 appliance cycles to off-peak hours (22:00–06:00)",
    aeroCreditsReward: 200,
    unlocked: false,
  },

  // ==================== CANOPY TIER ====================
  {
    id: "streak_lord",
    label: "Streak Lord",
    description: "Maintained a continuous 7-day streak of eco actions to reduce environmental footprint.",
    icon: "👑",
    tier: "canopy",
    category: "streak",
    unlockCondition: "Maintain a 7-day eco action streak",
    aeroCreditsReward: 350,
    unlocked: false,
  },
  {
    id: "monthly_warrior",
    label: "Monthly Warrior",
    description: "Completed all scheduled weekly eco quests within a single calendar month.",
    icon: "⚔️",
    tier: "canopy",
    category: "quest",
    unlockCondition: "Complete all weekly quests in a calendar month",
    aeroCreditsReward: 350,
    unlocked: false,
  },
  {
    id: "city_builder",
    label: "City Builder",
    description: "Constructed at least one of every structure type inside SkyforgeZero.",
    icon: "🏙️",
    tier: "canopy",
    category: "special",
    unlockCondition: "Place all 3 structure types in SkyforgeZero",
    aeroCreditsReward: 350,
    unlocked: false,
  },
  {
    id: "thousand_club",
    label: "Thousand Club",
    description: "Crossed a legendary threshold by earning 1,000 total Aero-Credits.",
    icon: "🏦",
    tier: "canopy",
    category: "rank",
    unlockCondition: "Earn 1,000 total Aero-Credits",
    aeroCreditsReward: 350,
    unlocked: false,
  },

  // ==================== STORM TIER ====================
  {
    id: "smog_slayer",
    label: "Smog Slayer",
    description: "Lowered the virtual city carbon dioxide indicator from 750 down below 400 in a single run.",
    icon: "💨",
    tier: "storm",
    category: "special",
    unlockCondition: "Drop city CO2 index from 750 to below 400 in one session",
    aeroCreditsReward: 500,
    unlocked: false,
  },
  {
    id: "eco_duelist",
    label: "Eco Duelist",
    description: "Defeated carbon rivals by winning 3 eco-duels against other users in the community.",
    icon: "🤺",
    tier: "storm",
    category: "social",
    unlockCondition: "Win 3 eco duels against other users",
    aeroCreditsReward: 500,
    unlocked: false,
  },
  {
    id: "ghost_load",
    label: "Ghost Load",
    description: "Achieved absolute zero peak-hour home standby appliance use for a full, consecutive week.",
    icon: "👻",
    tier: "storm",
    category: "grid",
    unlockCondition: "Zero peak-hour appliance use for an entire week",
    aeroCreditsReward: 500,
    unlocked: false,
  },
  {
    id: "referral_storm",
    label: "Referral Storm",
    description: "Persuaded 3 new users to join and complete their first sustainable footprint quest.",
    icon: "⚡",
    tier: "storm",
    category: "social",
    unlockCondition: "Refer 3 friends who complete their first quest",
    aeroCreditsReward: 500,
    unlocked: false,
  },

  // ==================== LEGEND TIER ====================
  {
    id: "solarpunk_achieved",
    label: "Solarpunk Achieved",
    description: "Designed a balanced microgrid dropping the city carbon index below 200 ppm.",
    icon: "☀️",
    tier: "legend",
    category: "special",
    unlockCondition: "Drop city CO2 index below 200 ppm",
    aeroCreditsReward: 1000,
    unlocked: false,
  },
  {
    id: "carbon_negative",
    label: "Carbon Negative",
    description: "Pioneered negative footprint status by offseting more carbon than you generated in a full month.",
    icon: "🌍",
    tier: "legend",
    category: "rank",
    unlockCondition: "Offset more CO2 than you emit in a full month",
    aeroCreditsReward: 1000,
    unlocked: false,
  },
  {
    id: "planetary_elder",
    label: "Planetary Elder",
    description: "Reached the absolute highest rank and completed the final milestone pathway of the grid.",
    icon: "🧙‍♂️",
    tier: "legend",
    category: "rank",
    unlockCondition: "Reach maximum rank (top tier on the milestone journey)",
    aeroCreditsReward: 1000,
    unlocked: false,
  },
  {
    id: "the_bubu_accord",
    label: "The Bubu Accord",
    description: "Unlocked all other 20 achievements to strike a balance between humanity and environment.",
    icon: "🐼",
    tier: "legend",
    category: "special",
    unlockCondition: "Unlock all other 20 badges",
    aeroCreditsReward: 1000,
    unlocked: false,
  },
];
